// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZDtGMdRyBwlQ4Ps4fx8PQ4yxDV18LA_E',
    appId: '1:1010804350142:web:4404cb98529841cb0b12ef',
    messagingSenderId: '1010804350142',
    projectId: 'spice-market-49a7b',
    authDomain: 'spice-market-49a7b.firebaseapp.com',
    storageBucket: 'spice-market-49a7b.firebasestorage.app',
    measurementId: 'G-KZG9WMGV80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDukwXgEuVAgA7D9Rzi-DAekFEjS7TCdHc',
    appId: '1:1010804350142:android:5283680665733e8e0b12ef',
    messagingSenderId: '1010804350142',
    projectId: 'spice-market-49a7b',
    storageBucket: 'spice-market-49a7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyjQMQRcbv-IBVRGuItcACLQrE9j5RnR4',
    appId: '1:1010804350142:ios:cb18599c55ef3f6f0b12ef',
    messagingSenderId: '1010804350142',
    projectId: 'spice-market-49a7b',
    storageBucket: 'spice-market-49a7b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyjQMQRcbv-IBVRGuItcACLQrE9j5RnR4',
    appId: '1:1010804350142:ios:cb18599c55ef3f6f0b12ef',
    messagingSenderId: '1010804350142',
    projectId: 'spice-market-49a7b',
    storageBucket: 'spice-market-49a7b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZDtGMdRyBwlQ4Ps4fx8PQ4yxDV18LA_E',
    appId: '1:1010804350142:web:f0c962584f8fc6550b12ef',
    messagingSenderId: '1010804350142',
    projectId: 'spice-market-49a7b',
    authDomain: 'spice-market-49a7b.firebaseapp.com',
    storageBucket: 'spice-market-49a7b.firebasestorage.app',
    measurementId: 'G-9W67D4VY18',
  );
}
